---
title: "Automating CVs with Google Drive"
subtitle: "A Step-by-Step Guide to Optimize Your Job Applications"
format:
  revealjs:
    title-slide-attributes:
      data-state: "hide-menubar"
    center: true
    theme: white
    transition: slide
    background-transition: fade
    controls-layout: bottom-right
    menu: false
    css: "css/style.css"
    section-divs: true
    simplemenu:
      barhtml:
        header: "<div class='menubar'><ul class='menu'></ul><div>"
      scale: 0.67
revealjs-plugins:
  - simplemenu
---

# Why Automate CV Submission? {data-stack-name="AutomatingCV"}

## Introduction  
Imagine personalizing your CVs and cover letters for every job application without manual effort. With **Google Apps Script**, you can automate this process and save time.

---

## What is Google Apps Script?  
Google Apps Script is an integrated scripting platform in Google, enabling automations such as:  
- Document personalization  
- PDF conversion  
- Automated email sending  

---

## Requirements for this Tutorial  
1. **Google Docs**: A cover letter template  
2. **Google Sheets**: A database of companies and specific information  
3. **Google Drive**: A folder to store the generated PDF files  

---

## Step 1: Create a Template in Google Docs  

1. **Open Google Docs and create a document**.  
2. Add your standard cover letter content.  
3. Insert keywords within angle brackets (`<<>>`) for customization, such as:  
   - `<<COMPANY>>`  
   - `<<POSITION>>`  
   - `<<RECRUITER>>`  

Example content:  

```text
[Your Address]
<<LOCATION>>
<<DATE>>
To the attention of <<RECRUITER>>
[Company Address]
<<COMPANY>>
Subject: Application for the position of <<POSITION>>

Dear <<RECRUITER>>,
...
[Your Name]
