project:
  type: website

website:
  title: "Mi Sitio Web"
  description: "Bienvenido a mi sitio web creado con Quarto."
  navbar:
    left:
      - text: "Inicio"
        href: "index.qmd"
      - text: "Acerca de"
        href: "about.qmd"
    right:
      - text: "English"
        href: "../en/index.qmd"
      - text: "Français"
        href: "../fr/index.qmd"